# Generated by Django 5.0.3 on 2024-03-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='link',
            field=models.TextField(),
        ),
    ]
